#!/usr/bin/env bash

logger "Refresh...."
if [ -a "${SNAP_DATA}/etc/ddclient/ddclient.conf" ]; then
    logger "Yay, ddclient.conf (old) exists"
    if [ -z "$(cat ${SNAP_DATA}/etc/ddclient/ddclient.conf)" ]; then
        cat "${SNAP_DATA}/etc/ddclient/ddclient.conf" > "${SNAP_DATA}/ddclient.conf"
    fi
    rm -rf "${SNAP_DATA}/etc" "${SNAP_DATA}/var"
else
    logger "Nay, ddclient.conf (old) does NOT exists"
fi
