name: ddclient-snap
base: core22
version: 'v3.11.2'
summary: "Update dynamic DNS entries for accounts on dynamic DNS services."
description: |
  Dynamic DNS services currently supported include: 
    - [services](https://github.com/ddclient/ddclient?tab=readme-ov-file#supported-services)
  
  Comments, suggestions and requests: use the issues on https://github.com/ddclient/ddclient/issues/new
  The code was originally written by Paul Burry and is now hosted and maintained through github.com.

  Please check out http://ddclient.net
grade: stable
confinement: strict

apps:
  ddclient-snap:
    environment:
      LC_ALL: "C.UTF-8"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: usr/local/bin/ddclient --daemon 300 -foreground
    command-chain:
      - env-wrapper
    daemon: simple
    plugs:
      - network
  exec:
    environment:
      LC_ALL: "C.UTF-8"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: usr/local/bin/ddclient
    command-chain:
      - env-wrapper
    plugs:
      - network

layout:
  /usr/bin/curl:
    symlink: $SNAP/usr/bin/curl
  /usr/local/etc/ddclient.conf:
    symlink: $SNAP_DATA/ddclient.conf
  /usr/local/var/cache/ddclient/ddclient.cache:
    bind-file: $SNAP_COMMON/ddclient.cache

parts:
  ddclient:
    plugin: autotools
    source: https://github.com/ddclient/ddclient.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    build-packages:
      - libplack-perl
      - libhttp-daemon-perl
      - libhttp-message-perl
      - libhttp-daemon-ssl-perl
      - libtest-mockmodule-perl
      - libtest-warnings-perl
    stage-packages:
      - libplack-perl
      - libhttp-daemon-perl
      - libhttp-daemon-ssl-perl
      - libhttp-message-perl
      - libwww-perl
      - libdata-validate-ip-perl
      - libio-socket-inet6-perl
      - libio-socket-ssl-perl
      - libjson-pp-perl
      - libsys-hostname-long-perl
      - perl
      - perl-base
      - perl-modules
      - curl
      #organize:
        #usr/local/bin/ddclient: bin/ddclient
    override-prime: |
      echo "PART INSTaLL:${CRAFT_PART_INSTALL}"
      sed -i "s#${CRAFT_PART_INSTALL}##" ${CRAFT_STAGE}/usr/local/bin/ddclient
      craftctl default
  local:
    plugin: dump
    source: src/
    organize:
      hooks: snap/hooks
